services:
    tb.transliterator:
        class: TB\Framework\Transliterator\Transliterator

    tb.utils.wordpress:
        class: TB\Framework\Util\WordPress

    tb.utils.twitter_bootstrap:
        class: TB\Framework\Util\TwitterBootstrap